---
logging:
  level:
    com.example: DEBUG

hello:
  greeting: Bonjour

# disable security for management endpoints:
management:
  security:
    enabled: false

endpoints:
  mappings:
    enabled: false
  beans:
    enabled: false
  shutdown:
    enabled: true

---
spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/todos
    username: todo_user
    password: secret
  jpa:
    generate-ddl: true

